name: "Development workflow"
on: 
    pull_request:  
        branches: ["main"]
jobs:
    lint:
        runs-on: ubuntu:latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v3

            - name: "Install Node"
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: yarn

            - name: "Install dependencies"
              run: yarn install

            - name: "Run ESLint"
              run: yarn lint

            - name: "Run Tests"
              run: yarn test

            - name: "Run build"
              run: yarn build
